name: Laravel Test - MariaDB & PostgreSQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-mariadb:
    name: Laravel with MariaDB ${{ matrix.mariadb-versions }}
    uses: ./.github/workflows/laravel-test.yml
    with:
      db-type: mysql
      db-version: ${{ matrix.mariadb-versions }}

    strategy:
      matrix:
        mariadb-versions: ["10", "11"]

  laravel-psql:
    name: Laravel with PostgreSQL ${{ matrix.pgsql-versions }}
    uses: ./.github/workflows/laravel-test.yml
    with:
      db-type: pgsql
      db-version: ${{ matrix.pgsql-versions }}

    strategy:
      matrix:
        pgsql-versions: ["16", "17"]
